name: "push example"
on: 
  workflow_dispatch:

  repository_dispatch:
    types:
      - deploy  
permissions:
  contents: write
jobs:
  report:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: firststep
        name: do some action
        env:
            CUSTOMER_FOLDER: 'data'
        run: | 
          ls
          cd $CUSTOMER_FOLDER
          ls
          date +%s > customerdata.txt
      - name: Commit report
        run: |
          pwd
          cd $CUSTOMER_FOLDER
          git config --global user.name 'Technical User'
          git config --global user.email 'technical@users.noreply.github.com'
          git add customerdata.txt
          git commit -am "Cluster info added"
          git push